{% set name = "napari-workflows" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-workflows-{{ version }}.tar.gz
  sha256: 85a5d405aa3433994e1b3e435b35437ed334b2d51ad824d042776affb43744fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - autopep8
    - dask-core
    - napari
    - numpy
    - python >=3.7

test:
  imports:
    - napari_workflows
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-workflows
  summary: Data structures for managing image processing workflows in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
